import type { MealItem, ShoppingItem } from "./types"

export type MockMealSeed = Omit<MealItem, "recipe_id" | "ingredients_summary"> & {
  recipe_id: string
  description: string
  ingredients: ShoppingItem[]
  tags: string[]
}

export const mealSeeds: MockMealSeed[] = [
  {
    type: "breakfast",
    time: "08:00",
    recipe_id: "mock-greek-yogurt-bowl",
    title: "Greek yogurt bowl",
    calories: 430,
    protein: 34,
    fat: 12,
    carbs: 48,
    description: "Creamy yogurt, berries, oats, and seeds for a calm high-protein morning.",
    ingredients: [
      { name: "Greek yogurt", amount: 220, unit: "g" },
      { name: "Blueberries", amount: 90, unit: "g" },
      { name: "Rolled oats", amount: 45, unit: "g" },
      { name: "Chia seeds", amount: 10, unit: "g" },
    ],
    tags: ["breakfast", "high protein", "quick"],
  },
  {
    type: "lunch",
    time: "12:45",
    recipe_id: "mock-salmon-rice-plate",
    title: "Salmon rice plate",
    calories: 690,
    protein: 44,
    fat: 25,
    carbs: 68,
    description: "Baked salmon with rice, cucumber, avocado, and a lemon-herb finish.",
    ingredients: [
      { name: "Salmon fillet", amount: 170, unit: "g" },
      { name: "Cooked rice", amount: 180, unit: "g" },
      { name: "Avocado", amount: 70, unit: "g" },
      { name: "Cucumber", amount: 100, unit: "g" },
    ],
    tags: ["lunch", "omega 3", "balanced"],
  },
  {
    type: "snack",
    time: "16:30",
    recipe_id: "mock-apple-almond-snack",
    title: "Apple almond snack",
    calories: 260,
    protein: 8,
    fat: 15,
    carbs: 30,
    description: "A simple snack with fruit, almonds, and cottage cheese.",
    ingredients: [
      { name: "Apple", amount: 1, unit: "pc" },
      { name: "Almonds", amount: 22, unit: "g" },
      { name: "Cottage cheese", amount: 100, unit: "g" },
    ],
    tags: ["snack", "simple"],
  },
  {
    type: "dinner",
    time: "19:30",
    recipe_id: "mock-chicken-vegetable-tray",
    title: "Chicken vegetable tray",
    calories: 650,
    protein: 52,
    fat: 22,
    carbs: 54,
    description: "Roasted chicken, potatoes, carrots, and greens on one tray.",
    ingredients: [
      { name: "Chicken breast", amount: 190, unit: "g" },
      { name: "Potatoes", amount: 220, unit: "g" },
      { name: "Carrots", amount: 120, unit: "g" },
      { name: "Olive oil", amount: 12, unit: "ml" },
    ],
    tags: ["dinner", "meal prep"],
  },
  {
    type: "breakfast",
    time: "08:15",
    recipe_id: "mock-spinach-omelette",
    title: "Spinach omelette",
    calories: 470,
    protein: 35,
    fat: 27,
    carbs: 24,
    description: "Egg omelette with spinach, feta, tomato, and toast.",
    ingredients: [
      { name: "Eggs", amount: 3, unit: "pcs" },
      { name: "Spinach", amount: 80, unit: "g" },
      { name: "Feta", amount: 35, unit: "g" },
      { name: "Whole-grain toast", amount: 1, unit: "slice" },
    ],
    tags: ["breakfast", "savory"],
  },
  {
    type: "lunch",
    time: "13:00",
    recipe_id: "mock-turkey-quinoa-bowl",
    title: "Turkey quinoa bowl",
    calories: 710,
    protein: 50,
    fat: 20,
    carbs: 78,
    description: "Lean turkey, quinoa, tomatoes, greens, and yogurt dressing.",
    ingredients: [
      { name: "Turkey mince", amount: 180, unit: "g" },
      { name: "Quinoa", amount: 170, unit: "g" },
      { name: "Cherry tomatoes", amount: 120, unit: "g" },
      { name: "Greek yogurt", amount: 60, unit: "g" },
    ],
    tags: ["lunch", "high protein"],
  },
  {
    type: "snack",
    time: "16:00",
    recipe_id: "mock-hummus-crunch",
    title: "Hummus crunch plate",
    calories: 310,
    protein: 11,
    fat: 14,
    carbs: 38,
    description: "Hummus with crisp vegetables and rye crackers.",
    ingredients: [
      { name: "Hummus", amount: 80, unit: "g" },
      { name: "Bell pepper", amount: 100, unit: "g" },
      { name: "Carrots", amount: 100, unit: "g" },
      { name: "Rye crackers", amount: 35, unit: "g" },
    ],
    tags: ["snack", "fiber"],
  },
  {
    type: "dinner",
    time: "19:15",
    recipe_id: "mock-beef-noodle-stir",
    title: "Beef noodle stir-fry",
    calories: 720,
    protein: 47,
    fat: 24,
    carbs: 78,
    description: "Beef strips, noodles, broccoli, and ginger-soy sauce.",
    ingredients: [
      { name: "Lean beef", amount: 170, unit: "g" },
      { name: "Noodles", amount: 190, unit: "g" },
      { name: "Broccoli", amount: 150, unit: "g" },
      { name: "Soy sauce", amount: 20, unit: "ml" },
    ],
    tags: ["dinner", "warm"],
  },
]

export const dayIndexes = [
  [0, 1, 2, 3],
  [4, 5, 6, 7],
  [0, 5, 2, 7],
  [4, 1, 6, 3],
  [0, 5, 6, 3],
  [4, 1, 2, 7],
  [0, 1, 6, 3],
]
