const TEXT = {
  "app.updated": "Обновлено",
  "app.attention": "Внимание",
  "error.loadTitle": "Не удалось загрузить данные",
  "error.loadHint": "Проверь backend или попробуй ещё раз.",
  "nav.primary": "Основная навигация",
  "nav.today": "Сегодня",
  "nav.week": "Неделя",
  "nav.profile": "Профиль",
  "nav.shopping": "Покупки",
  "common.kcal": "ккал",
  "common.grams": "г всего",
  "common.gram": "г",
  "common.protein": "Белок",
  "common.fat": "Жиры",
  "common.carbs": "Углеводы",
  "common.meals": "Приёмы",
  "common.loading": "Загружаем список...",
  "meal.breakfast": "Завтрак",
  "meal.lunch": "Обед",
  "meal.dinner": "Ужин",
  "meal.snack": "Перекус",
  "meal.second_snack": "Поздний перекус",
  "goal.lose": "Снижение веса",
  "goal.gain": "Набор мышц",
  "goal.maintain": "Баланс",
  "week.regenerate": "Пересобрать неделю",
  "week.calendar": "Календарь",
  "week.more": "Ещё",
  "week.daysLabel": "Дни плана",
  "week.day": "День",
  "week.fromTarget": "от цели",
  "week.protein": "Белок",
  "week.macros": "КБЖУ",
  "week.energyProfile": "Энергия",
  "week.caloriesTitle": "Калории по неделе",
  "week.dailyTarget": "цель в день",
  "week.chartLabel": "Калории по дням недели",
  "week.shortPlanTitle": "В сохранённой неделе только {{count}} дня",
  "week.shortPlanCopy":
    "Сгенерируйте свежий план на 7 дней, чтобы Сегодня, Неделя, Покупки и Календарь работали с полной неделей.",
  "week.onTarget": "в норме",
  "screen.back": "Назад",
  "home.todayPlanned": "Сегодня уже спланировано.",
  "home.heroCopy":
    "Mealy показывает главное: ближайший приём пищи, энергию дня и что подготовить дальше.",
  "home.kcalLeft": "Осталось {{count}} ккал в плане дня",
  "home.kcalOver": "{{count}} ккал сверх нормы",
  "home.addCalendar": "Добавить в календарь",
  "home.nextUp": "Ближайшее",
  "home.flexible": "Гибкое время",
  "home.prepareNext": "Дальше подготовить:",
  "home.dayRhythm": "Ритм дня",
  "home.dayRhythmTitle": "Приёмы пищи по порядку",
  "home.fullWeek": "Вся неделя",
  "home.anyTime": "Любое время",
  "home.recipes": "Рецепты",
  "home.recipesTitle": "Откройте блюдо, когда пора готовить",
  "home.macroTitle": "Баланс КБЖУ на сегодня",
  "home.macroEyebrow": "Распределение КБЖУ",
  "recipe.titleFallback": "Рецепт",
  "recipe.notAvailable": "Рецепт недоступен",
  "recipe.notAvailableSubtitle": "Не удалось найти это блюдо в текущем плане.",
  "recipe.notAvailableCopy":
    "Вернитесь в Сегодня или Неделю и выберите другую карточку.",
  "recipe.subtitle":
    "Карточка блюда с КБЖУ, ингредиентами, шагами готовки и покупками.",
  "recipe.anytime": "Любое время",
  "recipe.ready": "Можно готовить",
  "recipe.planControls": "Управление планом",
  "recipe.adjust": "Изменить блюдо",
  "recipe.replace": "Заменить блюдо",
  "recipe.replacing": "Заменяем...",
  "recipe.remove": "Убрать",
  "recipe.removing": "Убираем...",

  "recipe.ingredients": "Ингредиенты",
  "recipe.ingredientsTitle": "Что подготовить",
  "recipe.steps": "Рецепт",
  "recipe.stepsTitle": "Как готовить",
  "recipe.stepPrep": "Подготовьте и отмерьте все ингредиенты из списка.",
  "recipe.stepCook": "Приготовьте ингредиенты, которым нужна термообработка.",
  "recipe.stepCombine": "Соедините основу, белок, овощи и соус.",
  "recipe.stepServe": "Приправьте по вкусу и подайте в запланированной порции.",
  "recipe.openShopping": "Открыть покупки",
  "recipe.removeConfirm": "Убрать из плана?",
  "recipe.removeConfirmText": "Это блюдо будет убрано из плана дня.",
  "recipe.removeYes": "Да, убрать",
  "recipe.removeNo": "Оставить",
  "recipe.prepTime": "{{count}} мин",
  "shopping.title": "Список покупок",
  "shopping.subtitle": "Ингредиенты для текущего плана на {{count}} дней.",
  "shopping.grouped": "{{count}} позиций на неделю",
  "shopping.downloadPdf": "Получить список покупок в PDF",
  "shopping.loading": "Собираем список продуктов...",
  "shopping.emptyTitle": "Покупок пока нет",
  "shopping.emptyCopy":
    "Сгенерируйте план или откройте экран после готовности недели.",
  "shopping.clearChecked": "Сбросить отметки",
  "onboarding.brandSub": "Настройка плана питания",
  "onboarding.mode.create": "Создать",
  "onboarding.mode.signIn": "Войти",
  "onboarding.setup": "Настройка",
  "onboarding.title": "Соберите план на 7 дней",
  "onboarding.copy":
    "Заполните основные данные один раз. Mealy подготовит блюда, баланс питания и недельный ритм.",
  "onboarding.account": "Аккаунт",
  "onboarding.basics": "Начните с основного",
  "onboarding.savedProfile": "Войдите в сохранённый профиль",
  "onboarding.email": "Эл. почта",
  "onboarding.password": "Пароль",
  "onboarding.emailPlaceholder": "you@example.com",
  "onboarding.passwordPlaceholder": "Минимум 6 символов",
  "onboarding.bodyMetrics": "Параметры тела",
  "onboarding.cleanInputs": "Дайте планировщику точные данные",
  "onboarding.age": "Возраст",
  "onboarding.weight": "Вес, кг",
  "onboarding.height": "Рост, см",
  "onboarding.gender": "Пол",
  "onboarding.genderFemale": "Женский",
  "onboarding.genderMale": "Мужской",
  "onboarding.goalRhythm": "Цель и ритм",
  "onboarding.weekTone": "Настройте характер недели",
  "onboarding.activity": "Активность",
  "onboarding.goal": "Цель",
  "onboarding.preferences": "Предпочтения",
  "onboarding.lowActivity": "Низкая активность",
  "onboarding.lightActivity": "Лёгкая активность",
  "onboarding.moderateActivity": "Средняя активность",
  "onboarding.highActivity": "Высокая активность",
  "onboarding.veryActive": "Очень высокая",
  "onboarding.fatLoss": "Снижение веса",
  "onboarding.maintain": "Поддержание",
  "onboarding.gainMuscle": "Набор мышц",
  "onboarding.restrictionsReview": "Ограничения и проверка",
  "onboarding.guardrails": "Зафиксируйте важные ограничения",
  "onboarding.allergies": "Аллергии",
  "onboarding.disliked": "Нелюбимые ингредиенты",
  "onboarding.conditions": "Состояния",
  "onboarding.back": "Назад",
  "onboarding.continue": "Продолжить",
  "onboarding.starting": "Запускаем...",
  "onboarding.generate": "Сгенерировать неделю",
  "onboarding.preferencesPlaceholder": "Средиземноморская, много белка, рыба",
  "onboarding.allergiesPlaceholder": "орехи, молоко, яйца",
  "onboarding.dislikedPlaceholder": "брокколи, печень, лук",
  "onboarding.conditionsPlaceholder": "гастрит, диабет",
  "empty.todaySubtitle":
    "Здесь появится дневной центр питания после онбординга.",
  "empty.noWeek": "Нет активной недели",
  "empty.title": "Сгенерируйте первый план на 7 дней",
  "empty.copy":
    "Mealy подготовит блюда, неделю, рецепты и действия плана на основе профиля.",
  "empty.previewToday": "Ближайший приём пищи и прогресс дня",
  "empty.previewWeek": "Семь запланированных дней",
  "empty.actions": "Действия",
  "empty.previewActions": "Покупки, календарь и отправка",
  "empty.start": "Начать онбординг",
  "empty.generate": "Сгенерировать первую неделю",
  "profile.title": "Профиль",
  "profile.subtitle":
    "Измените параметры питания для следующей сгенерированной недели.",
  "profile.body": "Тело",
  "profile.coreMeasurements": "Основные параметры",
  "profile.restrictions": "Ограничения",
  "profile.foodGuardrails": "Пищевые правила",
  "profile.save": "Сохранить профиль",
  "profile.saving": "Сохраняем...",
  "profile.signOut": "Выйти",
  "profile.planningSection": "Параметры планирования",
  "profile.planningDesc":
    "Эти значения влияют на каждую сгенерированную неделю.",
  "generating.eyebrow": "ИИ составляет план",
  "generating.title": "Составляем вашу неделю",
  "generating.statusPending":
    "Создаём профиль питания и ставим план в очередь.",
  "generating.statusGenerating":
    "Подбираем рецепты, балансируем калории, формируем итоговую неделю.",
  "generating.statusReady": "Ваша неделя почти готова.",
  "generating.statusFailed": "Генерация не удалась.",
  "generating.errorTitle": "Не удалось завершить генерацию.",
  "generating.tryAgain": "Попробовать снова",
  "generating.cancel": "Отмена",
  "macro.p": "Б",
  "macro.f": "Ж",
  "macro.c": "У",
  "observability.title.generation": "Составляем план",
  "observability.title.result": "Проверка плана",
  "observability.eyebrow.generation": "Статус в реальном времени",
  "observability.eyebrow.result": "Проверка баланса",
  "observability.loading": "Загружаем диагностику генерации...",
  "observability.summaryHint":
    "Калории, макросы и ограничения проверяются до показа плана.",
  "observability.summary.ready": "План собран и готов к использованию.",
  "observability.summary.progress": "Составляем вашу неделю.",
  "observability.summary.active": "Текущий этап: {{step}}.",
  "observability.summary.review": "Доступна проверка плана.",
  "observability.step.profile": "Профиль",
  "observability.step.catalog": "Каталог",
  "observability.step.planner": "Планировщик",
  "observability.step.validation": "Проверка",
  "observability.step.context": "Контекст",
  "observability.step.generate": "Генерация",
  "observability.step.validate": "Валидация",
  "observability.step.reflection": "Сводка",
  "observability.step.source": "Источники",
  "observability.step.shopping": "Список покупок",
  "observability.status.completed": "Готово",
  "observability.status.pending": "Ожидание",
  "observability.status.running": "Выполняется",
  "observability.status.generating": "Составляем",
  "observability.status.failed": "Ошибка",
  "observability.status.limited": "Ограничено",
  "observability.message.profile": "Параметры питания и ограничения учтены.",
  "observability.message.catalog": "Рецепты подобраны под ваши ограничения.",
  "observability.message.planner": "Недельный ритм приёмов пищи собран.",
  "observability.message.validation": "Калории и макросы проверены.",
  "observability.message.context":
    "Учтены ограничения профиля и подходящие рецепты.",
  "observability.message.generate": "Недельный план сформирован.",
  "observability.message.validate": "Калории по дням сверены с целью.",
  "observability.message.reflection":
    "Показаны только безопасные итоговые показатели.",
  "observability.day": "День {{count}}",
  "observability.deviation": "Отклонение {{kcal}} ккал ({{pct}}%)",
  "observability.withinTarget": "В пределах цели",
  "observability.needsReview": "Нужна проверка",
} as const;

export type TextKey = keyof typeof TEXT;

export function text(key: TextKey, values?: Record<string, string | number>) {
  return Object.entries(values ?? {}).reduce(
    (result, [name, value]) => result.replaceAll(`{{${name}}}`, String(value)),
    TEXT[key],
  );
}

export function useText() {
  return { t: text };
}
